
[transforms.dedupe_fluentbit_evtlog_edges_has_session]
type = "dedupe"
inputs = ["route_fluentbit_evtlog.has_session"]
fields.match = ["NewLogonAccountName", "SubjectAccountName"]


[transforms.graph_fluentbit_evtlog_edges_has_session]
type = "remap"
inputs = ["dedupe_fluentbit_evtlog_edges_has_session"]
source = '''
Computer = to_string!(.Computer)
TargetUser = to_string!(.NewLogonSecurityID)

logon_type = get_enrichment_table_record("win_logon_types", {"id" : .LogonInformationLogonType}) ?? .LogonInformationLogonType

. = {
  "edge": {
    "kind": "HasSession", 
    "start": {
      "value": "{{ Computer }}",
      "match_by": "name"
    },
    "end": {
      "value": "{{ TargetUser }}",
      "match_by": "name",
    },
    "properties": {
      "isacl": false,
      "LogonType": logon_type.name
    }
  }
}
'''
