
[transforms.dedupe_fluentbit_evtlog_edges_admin_to]
type = "dedupe"
inputs = ["route_fluentbit_evtlog.admin_to"]
fields.match = ["Computer", "NewLogonSecurityID"]


[transforms.graph_fluentbit_evtlog_edges_admin_to]
type = "remap"
inputs = ["route_fluentbit_evtlog.admin_to"]
# inputs = ["dedupe_fluentbit_evtlog_edges_admin_to"]
source = '''
NewLogonSecurityID = to_string!(.NewLogonSecurityID)
Computer = upcase(to_string!(.Computer))

. = {
  "edge": {
    "kind": "AdminTo", 
    "start": {
      "value": "{{ NewLogonSecurityID }}",
      "match_by": "id"
    },
    "end": {
      "value": "{{ Computer }}",
      "match_by": "name",
    },
    "properties": {
      "isacl": false,
      "description": "This edge was created based on an elevated logon event. The principal may either be a direct member of local Administrators, or through one or more group memberships."
    }
  }
}
'''


[[tests]]
name = "AdminTo scenario 1: AdminTo deferred from Elevated logons"

[[tests.inputs]]
insert_at = "tf_fluentbit_winevtlog"
type = "log"

[tests.inputs.log_fields]
ActivityID = ""
Channel = "Security"
Computer = "winterfell.north.sevenkingdoms.local"
EventID = 4624
EventRecordID = 80455
Keywords = "0x8020000000000000"
Level = 0
Message = "An account was successfully logged on.\r\n\r\nSubject:\r\n\tSecurity ID:\t\tS-1-0-0\r\n\tAccount Name:\t\t-\r\n\tAccount Domain:\t\t-\r\n\tLogon ID:\t\t0x0\r\n\r\nLogon Information:\r\n\tLogon Type:\t\t3\r\n\tRestricted Admin Mode:\t-\r\n\tVirtual Account:\t\tNo\r\n\tElevated Token:\t\tYes\r\n\r\nImpersonation Level:\t\tImpersonation\r\n\r\nNew Logon:\r\n\tSecurity ID:\t\tS-1-5-21-1267327980-1800640824-2189074639-1001\r\n\tAccount Name:\t\tWINTERFELL$\r\n\tAccount Domain:\t\tNORTH.SEVENKINGDOMS.LOCAL\r\n\tLogon ID:\t\t0x2EA48B0\r\n\tLinked Logon ID:\t\t0x0\r\n\tNetwork Account Name:\t-\r\n\tNetwork Account Domain:\t-\r\n\tLogon GUID:\t\t{5047bfc5-c184-ab62-18a1-3f41f9ba4080}\r\n\r\nProcess Information:\r\n\tProcess ID:\t\t0x0\r\n\tProcess Name:\t\t-\r\n\r\nNetwork Information:\r\n\tWorkstation Name:\t-\r\n\tSource Network Address:\t10.3.10.11\r\n\tSource Port:\t\t50158\r\n\r\nDetailed Authentication Information:\r\n\tLogon Process:\t\tKerberos\r\n\tAuthentication Package:\tKerberos\r\n\tTransited Services:\t-\r\n\tPackage Name (NTLM only):\t-\r\n\tKey Length:\t\t0\r\n\r\nThis event is generated when a logon session is created. It is generated on the computer that was accessed.\r\n\r\nThe subject fields indicate the account on the local system which requested the logon. This is most commonly a service such as the Server service, or a local process such as Winlogon.exe or Services.exe.\r\n\r\nThe logon type field indicates the kind of logon that occurred. The most common types are 2 (interactive) and 3 (network).\r\n\r\nThe New Logon fields indicate the account for whom the new logon was created, i.e. the account that was logged on.\r\n\r\nThe network fields indicate where a remote logon request originated. Workstation name is not always available and may be left blank in some cases.\r\n\r\nThe impersonation level field indicates the extent to which a process in the logon session can impersonate.\r\n\r\nThe authentication information fields provide detailed information about this specific logon request.\r\n\t- Logon GUID is a unique identifier that can be used to correlate this event with a KDC event.\r\n\t- Transited services indicate which intermediate services have participated in this logon request.\r\n\t- Package name indicates which sub-protocol was used among the NTLM protocols.\r\n\t- Key length indicates the length of the generated session key. This will be 0 if no session key was requested."
Opcode = 0
ProcessID = 600
ProviderGuid = "{54849625-5478-4994-A5BA-3E3B0328C30D}"
ProviderName = "Microsoft-Windows-Security-Auditing"
Qualifiers = ""
RelatedActivityID = ""
Task = 12545
ThreadID = 7044
TimeCreated = "2025-09-14 18:05:08 -0400"
UserID = ""
Version = "0"
host = "10.3.10.10"
source_type = "fluent"
tag = "winevtlog.0"
timestamp = "2025-09-14T22:05:10.044136700Z"

[[tests.outputs]]
extract_from = "filter_fluentbit_evtlog"

[[tests.outputs.conditions]]
type = "vrl"
source = '''
assert!(is_string(.description))
assert!(.description == "An account was successfully logged on.", "Description not parsed from Message field content")
assert!(.NewLogonSecurityID == "S-1-5-21-1267327980-1800640824-2189074639-1001", "Subject Security ID not parsed from Message field content")
assert!(.NewLogonAccountName == "WINTERFELL$", "Subject Account Name not parsed from Message field content")
assert!(.NewLogonAccountDomain == "NORTH.SEVENKINGDOMS.LOCAL", "Subject Acount Domain not parsed from Message field content")
assert!(.LogonInformationLogonType == "3", "Subject Acount Domain not parsed from Message field content")
'''

[[tests.outputs]]
extract_from = "graph_fluentbit_evtlog_edges_admin_to"

[[tests.outputs.conditions]]
type = "vrl"
source = '''
assert!(.edge.start.value == "S-1-5-21-1267327980-1800640824-2189074639-1001", "Transform failed, start edge incorrect")
assert!(.edge.end.value == "WINTERFELL.NORTH.SEVENKINGDOMS.LOCAL", "Transform failed, end edge incorrect")
'''
