
[transforms.dedupe_fluentbit_evtlog_edges_has_session_2]
type = "dedupe"
inputs = ["route_fluentbit_evtlog.has_session_2"]
fields.match = ["Computer", "NewLogonNetworkAccountName", "NewLogonNetworkAccountDomain"]


[transforms.graph_fluentbit_evtlog_edges_has_session_2]
type = "remap"
# inputs = ["dedupe_fluentbit_evtlog_edges_has_session_2"]
inputs = ["route_fluentbit_evtlog.has_session_2"]
source = '''
Computer = upcase(to_string!(.Computer))
TargetUser = upcase(to_string!(.NewLogonNetworkAccountName))
TargetDomain = upcase(to_string!(.NewLogonNetworkAccountDomain))

logon_type = get_enrichment_table_record("win_logon_types", {"id" : .LogonInformationLogonType}) ?? .LogonInformationLogonType

. = {
  "edge": {
    "kind": "HasSession", 
    "start": {
      "value": "{{ Computer }}",
      "match_by": "name"
    },
    "end": {
      "value": "{{ TargetUser }}@{{ TargetDomain }}.SEVENKINGDOMS.LOCAL",
      "match_by": "name",
    },
    "properties": {
      "isacl": false,
      "LogonType": logon_type.name
    }
  }
}
'''


[[tests]]
name = "HasSession scenario 2: new credentials logon with credential exposure"

[[tests.inputs]]
insert_at = "tf_fluentbit_winevtlog"
type = "log"

[tests.inputs.log_fields]
ActivityID = ""
Channel = "Security"
Computer = "winterfell.north.sevenkingdoms.local"
EventID = 4624
EventRecordID = 80455
Keywords = "0x8020000000000000"
Level = 0
Message = "An account was successfully logged on.\r\n\r\nSubject:\r\n\tSecurity ID:\t\tS-1-5-21-1267327980-1800640824-2189074639-1000\r\n\tAccount Name:\t\tlocaluser\r\n\tAccount Domain:\t\tNORTH\r\n\tLogon ID:\t\t0x10E0C22\r\n\r\nLogon Information:\r\n\tLogon Type:\t\t9\r\n\tRestricted Admin Mode:\t-\r\n\tVirtual Account:\t\tNo\r\n\tElevated Token:\t\tYes\r\n\r\nImpersonation Level:\t\tImpersonation\r\n\r\nNew Logon:\r\n\tSecurity ID:\t\tS-1-5-21-1267327980-1800640824-2189074639-1000\r\n\tAccount Name:\t\tlocaluser\r\n\tAccount Domain:\t\tNORTH\r\n\tLogon ID:\t\t0x317A2B4\r\n\tLinked Logon ID:\t\t0x0\r\n\tNetwork Account Name:\thodor\r\n\tNetwork Account Domain:\tNORTH\r\n\tLogon GUID:\t\t{00000000-0000-0000-0000-000000000000}\r\n\r\nProcess Information:\r\n\tProcess ID:\t\t0x19b0\r\n\tProcess Name:\t\tC:\\Windows\\System32\\svchost.exe\r\n\r\nNetwork Information:\r\n\tWorkstation Name:\t-\r\n\tSource Network Address:\t::1\r\n\tSource Port:\t\t0\r\n\r\nDetailed Authentication Information:\r\n\tLogon Process:\t\tseclogo\r\n\tAuthentication Package:\tNegotiate\r\n\tTransited Services:\t-\r\n\tPackage Name (NTLM only):\t-\r\n\tKey Length:\t\t0\r\n\r\nThis event is generated when a logon session is created. It is generated on the computer that was accessed.\r\n\r\nThe subject fields indicate the account on the local system which requested the logon. This is most commonly a service such as the Server service, or a local process such as Winlogon.exe or Services.exe.\r\n\r\nThe logon type field indicates the kind of logon that occurred. The most common types are 2 (interactive) and 3 (network).\r\n\r\nThe New Logon fields indicate the account for whom the new logon was created, i.e. the account that was logged on.\r\n\r\nThe network fields indicate where a remote logon request originated. Workstation name is not always available and may be left blank in some cases.\r\n\r\nThe impersonation level field indicates the extent to which a process in the logon session can impersonate.\r\n\r\nThe authentication information fields provide detailed information about this specific logon request.\r\n\t- Logon GUID is a unique identifier that can be used to correlate this event with a KDC event.\r\n\t- Transited services indicate which intermediate services have participated in this logon request.\r\n\t- Package name indicates which sub-protocol was used among the NTLM protocols.\r\n\t- Key length indicates the length of the generated session key. This will be 0 if no session key was requested."
Opcode = 0
ProcessID = 600
ProviderGuid = "{54849625-5478-4994-A5BA-3E3B0328C30D}"
ProviderName = "Microsoft-Windows-Security-Auditing"
Qualifiers = ""
RelatedActivityID = ""
Task = 12545
ThreadID = 7044
TimeCreated = "2025-09-14 18:05:08 -0400"
UserID = ""
Version = "0"
host = "10.3.10.10"
source_type = "fluent"
tag = "winevtlog.0"
timestamp = "2025-09-14T22:05:10.044136700Z"

[[tests.outputs]]
extract_from = "filter_fluentbit_evtlog"

[[tests.outputs.conditions]]
type = "vrl"
source = '''
assert!(is_string(.description))
assert!(.description == "An account was successfully logged on.", "Description not parsed from Message field content")
assert!(.SubjectSecurityID == "S-1-5-21-1267327980-1800640824-2189074639-1000", "Subject Security ID not parsed from Message field content")
assert!(.SubjectAccountName == "localuser", "Subject Account Name not parsed from Message field content")
assert!(.SubjectAccountDomain == "NORTH", "Subject Acount Domain not parsed from Message field content")
assert!(.LogonInformationLogonType == "9", "Subject Acount Domain not parsed from Message field content")
'''

[[tests.outputs]]
extract_from = "graph_fluentbit_evtlog_edges_has_session_2"

[[tests.outputs.conditions]]
type = "vrl"
source = '''
assert!(.edge.start.value == "winterfell.north.sevenkingdoms.local", "Transform failed, start edge incorrect")
assert!(.edge.end.value == "HODOR@NORTH", "Transform failed, end edge incorrect")
'''